name: Build Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build APK
        run: chmod +x ./gradlew && ./gradlew assembleRelease

      - name: Get version
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >>$GITHUB_OUTPUT

      - name: Rename APK
        run: |
          mkdir artifacts
          for file in app/build/outputs/apk/release/*.apk; do
            if [[ $file =~ app-(.?*)release.apk ]]; then
              abi="${BASH_REMATCH[1]}"
              mv "$file" "artifacts/MY-Android-TV-${{ steps.version.outputs.version }}-${abi}.apk"
            fi
          done

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          name: v${{ steps.version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          allowUpdates: true
          artifacts: artifacts/*
